# Generated by Django 4.2.7 on 2023-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_osoba_data_dodania_delete_person_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True),
        ),
    ]
