# Generated by Django 4.2.7 on 2023-11-22 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_osoba_imie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
    ]
