# Generated by Django 4.2.7 on 2023-11-23 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_osoba_data_dodania_alter_osoba_imie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
