# Generated by Django 4.2.7 on 2023-11-23 11:16

from django.db import migrations, models
import django.utils.timezone
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[polls.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=50, validators=[polls.models.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=70, validators=[polls.models.validate_alpha]),
        ),
    ]
