# Generated by Django 4.2.7 on 2023-11-29 19:03

from django.db import migrations, models
import django.utils.timezone
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_osoba_data_dodania_alter_osoba_imie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now, validators=[polls.models.validate_past_date]),
        ),
    ]
