# Generated by Django 4.2.7 on 2023-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_osoba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
